site_name: Reimbursement Tracking System

nav:
  - Overview: index.md
  - Functional Documentation: functional.md
  - Use Case: bus-sys-use.md
  - Technical Documentation: technical.md
  - API Documentation: api.md
  - Sast & Dast Reports: sast.md
  - Test Planning: test.md

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

  features:
    - navigation.instant
  hide:
    - footer
plugins:
  - search


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

